# Generated by Django 3.0 on 2021-12-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20211219_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='ComentarioPosteosUsuarios',
        ),
        migrations.AlterField(
            model_name='comentarioposteosusuarios',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Altapost'),
        ),
    ]
