# Generated by Django 3.0 on 2021-12-19 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20211219_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentarioPosteosUsuarios',
            new_name='Comentario',
        ),
    ]
