# Generated by Django 3.0 on 2021-12-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comentariosobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='altapost',
            name='fecha_elaboracion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='comentariosobj',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.Objetivo'),
        ),
    ]
