# Generated by Django 3.0 on 2021-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211219_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altapost',
            name='fecha_elaboracion',
            field=models.DateField(auto_now=True),
        ),
    ]
